### ISSUE TITLE
No way to actually set the site or sub_wikia in Python3

### ISSUE THREAD

**Issue by etopian** [Timidger/Wikia#10]
This does not seem to work with Python 3. set_subwikia and set_wiki both do not work and the method seems to be missing from the module. Also need to fix documentation.

**Comment by Timidger** [comment]
Wow, whoops! I haven't looked the readme in a while. My mistake. Yeah, there is no `set_subwikia` or `set_wiki`, you do that in each method (so in the first example, you actually do `wikia.summary("Runescape", "Banshee")`. I'll fix the documentation immediately.
